### ISSUE TITLE
Improve labels for the measurements table column names

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#105]
The current implementation has the following:

![image](https://cloud.githubusercontent.com/assets/313942/20576517/45d0cdaa-b18c-11e6-8120-81d35968c188.png)

I suggest we show the following:

- [ ] when only quantity is available, show code meaning for quantity
- [ ] when quantity and derivation both are available, show code meaning for derivation
- [ ] when code meaning exceeds some length threshold, abbreviate to that length threshold
- [ ] always show quantity + derivation (when available) + units in the tooltip for both the column header and the cell content

Feedback is welcomed!

**Comment by fedorov** [comment]
I suggest (if not very complicated) to implement the steps above before project week, and then at the project week discuss how LabelStatistics can be implemented in an extensible and incorporate query of the quantity/units codes as a plugin API.

**Comment by che85** [comment]
That's not trivial and not that easy to do. The tableview is based on the model [1], which controls what is displayed. It reacts to modifications of the MRMLNode.

In order to get it working in the proposed way, we would need to implement another model which is specific for our quantitative reporting and has access to all those information like the quanity and derivation.

I need to think about it and I'll try to find an easy solution.

[1] https://github.com/Slicer/Slicer/blob/eefeac9286f48552e8418a11f412b2823a09b407/Libs/MRML/Widgets/qMRMLTableModel.h

**Comment by lassoan** [comment]
We could improve vtkMRMLTableNode to support metadata for each column, so that for each column where we could store unit, code value, code scheme designator, code meaning, tooltip text, ... Updating table view to use this metadata (show in tooltip, etc) would be quite easy. Metadata could be stored in the MRML node and written to a "standard" csv schema file (this would address the issue of wrongly guessing column types and automated export of csv file to database).

Unfortunately, there doesn't seem to be any very widely used standard schema but there are some simple ones that we could quite easily adopt. For example:
http://frictionlessdata.io/guides/json-table-schema/
http://specs.frictionlessdata.io/json-table-schema/

There are also standards that store the schema inside the csv file, for example:
http://jenit.github.io/linked-csv/
But this is a bit more invasive, makes the csv files more complex - so probably separate schema files are better.

**Comment by che85** [comment]
So would that be another tablemodel which is specifically designed for taking json schema?

**Comment by lassoan** [comment]
No, we would keep using the same table model, it would be just improved.

MRML node would be serialized to/from two files (csv+schema) instead of just a .csv file.

In memory, all data would be stored in the node. Values and some metadata (such as column type) would be obviously stored in vtkTable. Additional metadata could be stored in either vtkTable (e.g., in field data; or encoded in the column name with specially formatting) or in the MRML node.

**Comment by lassoan** [comment]
@fedorov Maybe you could ask around qiicr collaborators how they import (or would like to import)measurement results in csv files into their databases. We could implement their preferred schema in Slicer's table storage node.

**Comment by fedorov** [comment]
@lassoan why can't we just use the component of the existing JSON schema that we use in dcmqi for communicating measurements back and forth between DICOM and non-DICOM? See https://github.com/QIICR/dcmqi/blob/master/doc/sr-tid1500-ct-liver-example.json#L45-L143

It is quite simple, it is formalized by a schema, it maps to DICOM, we have tools for going from DICOM to CSV, we don't need to come up with yet another schema....

**Comment by lassoan** [comment]
Yes, sure, if we have something that may be already usable then we should definitely try that. Can you send examples (corresponding DICOM, schema, csv files)?

**Comment by lassoan** [comment]
The linked json files are nice - do you have corresponding csv files?
I would of course prefer to work only with fully structured data, such as json, xml, dicom sr, etc. but the reality is that most people use spreadsheets for manual editing and analysis. So, we have to have a robust way of converting between json<->csv(+schema).

**Comment by fedorov** [comment]
We don't support csv+schema route. dcmqi can do JSON<->DICOM SR TID1500, and we have a separate tool for DICOM SR TID1500 -> csv: https://github.com/QIICR/dsr2csv

I am open to discussion how to make it more approachable to most people, I agree, at least partially, with your concern...

**Comment by fedorov** [comment]
Sample DICOM SR TID1500 dataset: https://github.com/QIICR/dcmqi/blob/master/data/sr-example/sr.dcm

**Comment by fedorov** [comment]
dcmqi DICOM SR TID1500 converter parameters schema: https://github.com/QIICR/dcmqi/blob/master/doc/sr-tid1500-schema.json

**Comment by che85** [comment]
@lassoan Did you take a look at the json files? Do you have any comments, suggestions regarding the structure?

**Comment by che85** [comment]
@fedorov I think this issue can be closed, right?
