### ISSUE TITLE
API to better handle visibility of individual UI elements

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#143]

**Comment by cpinter** [comment]
As far as I know @lassoan took this task, please assign to him

**Comment by che85** [comment]
The following components should be directly accessible from python:
* (maybe) UndoRedoButtonBox
  * UndoButton
  * RedoButton,
* EffectsGroupBox
* OptionsGroupBox
* MaskingGroupBox
* AddSegmentButton
* RemoveSegmentButton
* CreateSurfaceButton
* segment table and the status (label?) on top of it.

It might make sense to hold a list of UI component object names which should be accessible by developers.

```
getAccessibleUIComponents()
```

We could then easily access those components by calling 
```
getUIComponentByObjectName(..)
```
For being able to configure available effects I suggest to add something like 

```
setAvailableEffects([Paint, Draw, Erase, ...])
```

**Comment by che85** [comment]
@cpinter Sorry I wasn't sure.

**Comment by lassoan** [comment]
I would prefer to control what developers can change in the widget to make sure we can keep the editor widget appearance and behavior consistent across all modules (and if you have good ideas for improvements then not only Reporting but all other modules should use that). For example, we could develop maybe 2-3 alternative layouts (normal, space-saving, horizontal) with a few options (show/hide buttons and sections), instead of just letting developers move controls around randomly (that would be hard to control and maintain).
Could you write what are the specific changes that you need in the appearance or behavior?

setAvailableEffects([Paint, Draw, Erase, ...]) is a separate story, I'll add a new ticket for that.

**Comment by fedorov** [comment]
@che85 can you please respond?

**Comment by che85** [comment]
@lassoan Why not exposing all components? I as a developer want to be free in how to organize the UI elements. I don't agree with having predefined layout unless you have a designer who did some research on how to propose components the best way to users.

A UI should always be space-saving but highlighting the important components for guaranteeing the best possible user experience. If you want developers to reuse your components, you should either give them freedom in how to organize the UI.

For QuantitativeReporting I just want to be as flexible as possible and hide components of the SegmentEditor that I don't want to get exposed to the user.

Who would define how normal, space-saving and horizontal will look like?

**Comment by lassoan** [comment]
> don't agree with having predefined layout unless you have a designer

GUIs are always problematic, as it is difficult to gather hard evidence and everybody has his own opinion. Don't expect anything from UX designers, unfortunately more often they make more harm than good.

What I would like to use your insights and experience and improve the common widget instead of letting everybody do random customizations. It doesn't have to be one exact layout: we can define a few layouts (optimized for different purposes) and also have a number of options to customize them.

You can of course still do anything you want, as Qt enables that already, but I would like to minimize these random customizations for two reasons: make GUI more consistent for user and reduce the chance of breaking things in your module by making changes in Slicer core.

So, please propose specific changes in the layout and all options that you would like to control. Also, try to provide rationale for the changes so that we can consolidate all the ideas, needs, and solutions with all other modules where the editor widget is used.

**Comment by fedorov** [comment]
@lassoan Christian proposed the specific items he would like to be able to control in this comment: https://github.com/QIICR/QuantitativeReporting/issues/143#issuecomment-283467948. Is this not detailed enough, or is he asking for more flexibility than you would prefer to allow?

**Comment by lassoan** [comment]
The above list of widgets to expose is not enough (they are already exposed anyway, just not explicitly allowed). I would need to know what are the custom layout(s) and options we should support, and also information on why these are useful, what are they optimized for.

**Comment by lassoan** [comment]
I've implemented effect list customization. Looking forward to getting more info from Christian to implement the rest of widget customization. If you already have a script that makes the widget look the way you like it then that could work as a specification, too. Or just send screenshots or sketches.

**Comment by che85** [comment]
@lassoan This is how it's implemented for quantitative Reporting right now.

![image](https://cloud.githubusercontent.com/assets/10195822/24223898/a99b7312-0f2e-11e7-9cd7-daae8395c2c4.png)

**Comment by che85** [comment]
When no effect is selected, those UI components below the undo/redo are in my opinion unnecessary 

![image](https://cloud.githubusercontent.com/assets/10195822/24223943/f58f5752-0f2e-11e7-84ad-1e8bb48a3479.png)

**Comment by che85** [comment]
Instructions like the following should be concealable

![image](https://cloud.githubusercontent.com/assets/10195822/24223992/38d43320-0f2f-11e7-9f42-360e0c47188e.png)

**Comment by fedorov** [comment]
I agree with Christian's observations.

**Comment by che85** [comment]
The following checkboxes could go into a horizontal layout in order to save space
![image](https://cloud.githubusercontent.com/assets/10195822/24224078/9ba8eb26-0f2f-11e7-8bc8-89c47fdd59e6.png)

**Comment by che85** [comment]
There should not be that much space under the dropdown

![image](https://cloud.githubusercontent.com/assets/10195822/24224143/ece88df2-0f2f-11e7-8e98-1d7b456e2aa0.png)

**Comment by che85** [comment]
The newer version of the SegmentEditor looks a bit different:

![image](https://cloud.githubusercontent.com/assets/10195822/24253092/bbef38f0-0fb5-11e7-9361-af232878bcf4.png)

What I notice here is that the background of the icons should be transparent
![image](https://cloud.githubusercontent.com/assets/10195822/24253115/cbe42bd0-0fb5-11e7-8ef8-5c8a270bb00e.png)

the same way it is here:
![image](https://cloud.githubusercontent.com/assets/10195822/24253152/e3ea086c-0fb5-11e7-99d2-b9376bfdb9d6.png)
![image](https://cloud.githubusercontent.com/assets/10195822/24253167/eb3a2e94-0fb5-11e7-8e63-7a67bf2430ff.png)

**Comment by lassoan** [comment]
I've implemented all suggestions (except one is still WIP, pending a CTK merge):
* When no effect is selected, those UI components below the undo/redo are in my opinion unnecessary => done
* Instructions like the following should be concealable => I've implemented collapse option for fitted text browser (https://github.com/commontk/CTK/pull/703). It'll allow showing only a short single-line help text and users can click on it to see more details. This PR need to be integrated before finalizing the implementation: https://github.com/commontk/CTK/pull/704
* The following checkboxes could go into a horizontal layout in order to save space => DONE
* There should not be that much space under the dropdown => There is actually no space at all, only if widget must fill a larger area then the effect options widget is expanded. Let me know if there is any layout where you see space here while there are other widgets that could use the space.

**Comment by lassoan** [comment]
> What I notice here is that the background of the icons should be transparent

Should I remove white background from all the icons?

**Comment by che85** [comment]
Thanks a lot. I am looking forward to testing it. 

I would always remove the background from icons ...
> Should I remove white background from all the icons?

**Comment by che85** [comment]
@lassoan 

The options groupbox is still visible on the current nightly even when there is no effect is selected.

![image](https://cloud.githubusercontent.com/assets/10195822/24616568/855c64ae-185f-11e7-97b2-7f01e4c8fa4c.png)

Another thing that not quite belong here is that the Segment Editor creates a vtkMRMLSegmentationNode once the Segment Editor is entered (which is also the case when opening Quantitative Reporting)

**Comment by che85** [comment]
@lassoan I just noticed that it would be great to have a read only mode for the Segment Editor. In case that we want to load a "completed" SR, the user should neither be able to add/remove any segments nor modify any of the segments. Therefore I would suggest to expose to the developers the button(s) or buttongroupbox and the effects parent which could be disabled.

Otherwise another solution would be to implement a readonly mode on side of the Segment Editor. I can imagine that users not always want to enable further editing of segmentations.

Other than that the segments table should always allow selection but not modification of name or terminology.

What do you think?

**Comment by lassoan** [comment]
What would you show in read-only mode? Only the segment list?

**Comment by che85** [comment]
Showing the buttons and everything is fine. I would just disable the mentioned components.

**Comment by che85** [comment]
I would almost go that far and set an attribute for vtkMRMLSegmentationNodes to be readonly.

That's how I am doing it right now in Quantitative Reporting

**Comment by che85** [comment]
It would also be great to either expose the `SegmentsTableView` to the developer because I am currently setting the readonly for that as follows:

```
self.segmentEditorWidget.table.setReadOnly(True)
```

otherwise it could just be implemented with the readonly in the Segment Editor itself so that the developer don't need direct access to `SegmentsTableView`

**Comment by lassoan** [comment]
Icons fixed (they are nicer and more consistent; no white background in any of them).

> The options groupbox is still visible on the current nightly even when there is no effect is selected.
You need to have a widget in the editor widget that can expand (otherwise the effect list would jump up/down depending on what effect you select). This expanding widget was the options groupbox, but now I hide it completely and add an invisible frame instead.

**Comment by lassoan** [comment]
I've probably committed the changes after the nightly build cutoff time, so you'll see these changes on Wednesday's nightly build.

**Comment by lassoan** [comment]
This issue is getting very long. Starting new discussion about read-only editor in #152.

**Comment by che85** [comment]
@lassoan Thanks for the icons. Looks far better!

**Comment by che85** [comment]
@lassoan Can you also expose `SegmentationNodeComboBox` and `masterVolumeNodeSelector`?

**Comment by che85** [comment]
@lassoan And please don't forget to expose the `SegmentsTableView` since I need this as well for reacting to segment selection changes

**Comment by lassoan** [comment]
Could I expose table and node selector methods and events that you need on the editor widget's API instead of exposing the widgets themselves?
1. It would make the widget simpler to use for developers.
2. We could make sure those custom methods and events remain functional, even if internals of the editor widget changes.
3. We could prevent any potential misuse (unexpected changes in the internal widgets could make the editor widget's state inconsistent; this inconsistency may not be obvious, problems may occur in certain use cases only, and potentially in the future, as the editor widget code is changed).

Sorry for being so complicated, but for long-term maintenance and robustness of the widget it's really important to have a clear API (instead of just letting developers freely change internals of the widget, without knowing all possible consequences in the present and in the future).

**Comment by che85** [comment]
That's fine. I need to do the following:

```
masterVolumeNodeSelector.addAttribute("vtkMRMLScalarVolumeNode", "DICOM.instanceUIDs", None)
```

```
segmentationNodeSelector.setCurrentNode(segmentationNode)
```

```
tableWidget.selectionModel().selectionChanged.connect .....
```
Maybe you can add some functionality for selecting a specific segment via index from the SegmentTable and providing a getter for getting the selected index?

**Comment by lassoan** [comment]
Added the missing APIs - see https://github.com/Slicer/Slicer/commit/538f9f1ad9ade8f6f806e1190d9b2e7b17c549e5

To select n-th segment, use editorWidget.setCurrentSegmentID(segmentation.GetNthSegmentID(n)).

**Comment by che85** [comment]
@lassoan Thanks for all the work. It seems not to be in todays nightly build so I will test tomorrow ant let you know.
