### ISSUE TITLE
Running tests requiring measurement to be saved are blocking.

### ISSUE THREAD

**Issue by jcfr** [QIICR/QuantitativeReporting#257]
Running tests requiring measurement saving are blocking.

https://github.com/QIICR/QuantitativeReporting/blob/962ed63cc84d943db95076e6320e33a19e661026/QuantitativeReporting/QuantitativeReporting.py#L90-L96

## Steps to reproduce

```
ctest -R QuantitativeReportingTests
```

Screenshot captured on "overload" windows dashboard:

![image](https://user-images.githubusercontent.com/219043/109515519-2a0a1c00-7a75-11eb-8b84-426d67f8e69c.png)

## Expected behavior

User interaction should not be expected when running Slicer dashboard

## Environment
- Slicer version: Slicer-4.13 Slicer/Slicer@4ec6541a620aa24559f70c65d363c1da3682902a
- Operating system: NA

**Comment by jcfr** [comment]
cc: @sjh26 @lassoan  @pieper

**Comment by fedorov** [comment]
Is this something that should be handled better by Slicer applicationLogic, in the testing framework, or fixed in QR? 

It might be that most intuitive way to fix this is be to populate user name with some default value, and prompt the user to change it when the application is launched for the first time.

**Comment by pieper** [comment]
Our traditional approach is not to use blocking dialogs when in test mode, so updating QR would be most convenient.

On the other hand having a default value of something like "Not Specified" for the user and similar field is what I do in other code.
